// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANgfCtpejsNrJkhMPdqnHjH3asRoCj2bc',
    appId: '1:795264122204:web:b41e01400ac040253c9599',
    messagingSenderId: '795264122204',
    projectId: 'maternal-healthcare-app',
    authDomain: 'maternal-healthcare-app.firebaseapp.com',
    storageBucket: 'maternal-healthcare-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOnqvvIumiqX93kIc1aOMERarm32-2c5E',
    appId: '1:795264122204:android:1e56fdf2491792193c9599',
    messagingSenderId: '795264122204',
    projectId: 'maternal-healthcare-app',
    storageBucket: 'maternal-healthcare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7VNQQVMgq3ZJu7l1d_cdZI9mFEwy4_vM',
    appId: '1:795264122204:ios:b3b1b84cb71aca8e3c9599',
    messagingSenderId: '795264122204',
    projectId: 'maternal-healthcare-app',
    storageBucket: 'maternal-healthcare-app.firebasestorage.app',
    iosBundleId: 'com.example.maternalhealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7VNQQVMgq3ZJu7l1d_cdZI9mFEwy4_vM',
    appId: '1:795264122204:ios:b3b1b84cb71aca8e3c9599',
    messagingSenderId: '795264122204',
    projectId: 'maternal-healthcare-app',
    storageBucket: 'maternal-healthcare-app.firebasestorage.app',
    iosBundleId: 'com.example.maternalhealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt4jX8j8ESJFz-EBDwWNf2DfpP1ogeIuY',
    appId: '1:795264122204:web:beb1415d4f45bea63c9599',
    messagingSenderId: '795264122204',
    projectId: 'maternal-healthcare-app',
    authDomain: 'maternal-healthcare-app.firebaseapp.com',
    storageBucket: 'maternal-healthcare-app.firebasestorage.app',
  );
}
